language: go

go:
  - 1.7.x
  - 1.8.x
  - 1.9.x
  - tip

install:
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get ./...

script:
  - test -z $(goimports -l nethttp)
  - golint -set_exit_status ./...
  - go test -v -cover -race ./...
